plugins:
  topic_curation_enabled:
    default: true
    client: true
  topic_curation_title:
    default: "Button description here.."
    client: true
  topic_curation_label:
    default: "Curator"
    client: true
  topic_curation_form_title:
    default: "Curation Form"
    client: true
  topic_curation_group_names:
    client: true
    type: list
    default: ''
  topic_curation_group_names_to_render_textboxes:
    client: true
    type: list
    default: ''